---
title: "Sleep_Report"
author: "Nima Hamedani-Raja"
date: "25/06/2020"
output: 
  html_document: 
    fig_height: 6
    fig_width: 10
    keep_md: yes
    toc: yes
---

# INIT

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r init}
source("init.R")
```

# daily_sleep

```{r daily_sleep}
source("sleep_daily.R")

print(sleep_daily_p1)
print(sleep_daily_p2)
```

# 24h_rolling  

```{r 24h_rolling}
source("sleep_24h.R")

DF_24h_summary %>% 
  mutate(sleep_24h = sleep_24h / 60) %>%
  filter(difftime(Date, min(Date), units = "days") >= 1) %>% 
  arrange(Date) %>% 
  ggplot(aes(x = Date, y = sleep_24h)) + geom_line(colour = "blue")

DF_24h_summary %>% 
  mutate(sleep_24h = sleep_24h / 60) %>%
  filter(difftime(Date, min(Date), units = "days") >= 1) %>% 
  filter(difftime(Sys.time(), Date, units = "days") <= 7) %>%
  arrange(Date) %>% 
  ggplot(aes(x = Date, y = sleep_24h)) + geom_line(colour = "blue")
```

# sleep_24h_distribution

```{r sleep_24h_distribution}
source("sleep_24h_distribution.R")

rbind(sleep24h_distribution_summary_all, 
      sleep24h_distribution_summary_last7, 
      sleep24h_distribution_summary_last28) %>%
  ggplot(aes(x = sleep_24h_value, weight = num_minutes, group = subset, colour = subset)) + 
  geom_density()

rbind(sleep24h_distribution_summary_all, 
      sleep24h_distribution_summary_last7, 
      sleep24h_distribution_summary_last28) %>%
  ggplot(aes(x = subset, y = sleep_24h_value, weight = num_minutes, fill = subset)) + 
  geom_boxplot(outlier.alpha = 0)

rbind(sleep24h_distribution_summary_all, 
      sleep24h_distribution_summary_last7, 
      sleep24h_distribution_summary_last28) %>%
  arrange(sleep_24h_value) %>%
  group_by(subset) %>%
  mutate(num_minutes_cdf = cumsum(num_minutes)) %>%
  ungroup() %>%
  ggplot(aes(x = sleep_24h_value, y = num_minutes_cdf, colour = subset)) + 
  geom_line()
```

# nap

```{r nap}
source("nap_desctiptive.R")

rbind(
  DF_aft %>%
    mutate(subset = "all"),
  DF_aft %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 7) %>% 
    mutate(subset = "last 7 days"),
  DF_aft %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 28) %>% 
    mutate(subset = "last 28 days")) %>%
  # filter(Date != '2020-06-17') %>% 
  ggplot(aes(x = nap_start_time, colour = subset)) + geom_density()

rbind(
  DF_aft %>%
    mutate(subset = "all"),
  DF_aft %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 7) %>% 
    mutate(subset = "last 7 days"),
  DF_aft %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 28) %>% 
    mutate(subset = "last 28 days")) %>%
  # filter(Date != '2020-06-17') %>% 
  ggplot(aes(x = nap_end_time, colour = subset)) + geom_density()

rbind(
  DF_aft %>%
    mutate(subset = "all"),
  DF_aft %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 7) %>% 
    mutate(subset = "last 7 days"),
  DF_aft %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 28) %>% 
    mutate(subset = "last 28 days")) %>%
  filter(Date != '2020-06-17') %>% 
  ggplot(aes(x = nap_length, colour = subset)) + geom_density()

DF_aft %>% 
  mutate(recent = difftime(Sys.time(), Date, units = "days") <= 7) %>%
  ggplot(aes(x = nap_start_time, y = nap_end_time, label = day_month)) + 
  geom_point(colour = "green") +
  geom_text(aes(colour = recent)) + 
  geom_smooth(method = "lm") + 
  theme(legend.position = "none")

DF_aft %>% 
  # filter(Date != '2020-06-17') %>% 
  select(Date, nap_start_time, nap_end_time) %>% 
  melt(id.vars = "Date") %>% 
  ggplot(aes(x = Date, y = value, colour = variable)) + 
  geom_line() + geom_point()

DF_aft %>% 
  # filter(Date != '2020-06-17') %>% 
  ggplot(aes(x = Date, y = nap_length))+ 
  geom_bar(stat = "identity", fill = "blue")

prob_nap %>% ggplot(aes(x = time, y = prob)) + geom_point(colour = "blue")

rbind(
  get_prob_nap_start(
    DF_aft, "All"),
  get_prob_nap_start(
    DF_aft %>% filter(difftime(Sys.time(), Date, units = "days") <= 7), "Last 7 days"),
  get_prob_nap_start(
    DF_aft %>% filter(difftime(Sys.time(), Date, units = "days") <= 28), "Last 28 days")) %>% 
  ggplot(aes(x = time, y = prob, colour = subset)) + geom_line()

rbind(
  get_prob_nap_end(
    DF_aft, "All"),
  get_prob_nap_end(
    DF_aft %>% filter(difftime(Sys.time(), Date, units = "days") <= 7), "Last 7 days"),
  get_prob_nap_end(
    DF_aft %>% filter(difftime(Sys.time(), Date, units = "days") <= 28), "Last 28 days")) %>% 
  ggplot(aes(x = time, y = prob, colour = subset)) + geom_line()
```

# night

```{r night}
source("night_descriptive.R")

rbind(
  DF_night %>%
    mutate(subset = "all"),
  DF_night %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 7) %>% 
    mutate(subset = "last 7 days"),
  DF_night %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 28) %>% 
    mutate(subset = "last 28 days")) %>%
  # filter(Date != Sys.Date()) %>%
  ggplot(aes(x = night_start_time, colour = subset)) + geom_density()

rbind(
  DF_night %>%
    mutate(subset = "all"),
  DF_night %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 7) %>% 
    mutate(subset = "last 7 days"),
  DF_night %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 28) %>% 
    mutate(subset = "last 28 days")) %>%
  # filter(Date != '2020-06-17') %>% 
  filter(Date != Sys.Date()) %>%
  ggplot(aes(x = night_end_time, colour = subset)) + geom_density()

rbind(
  DF_night %>%
    filter(!(Date == Sys.Date() & strftime(night_start, format="%H:%M:%S") < "16:00:00")) %>%
    mutate(subset = "all"),
  DF_night %>%
    filter(!(Date == Sys.Date() & strftime(night_start, format="%H:%M:%S") < "16:00:00")) %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 7) %>% 
    mutate(subset = "last 7 days"),
  DF_night %>%
    filter(!(Date == Sys.Date() & strftime(night_start, format="%H:%M:%S") < "16:00:00")) %>%
    filter(difftime(Sys.time(), Date, units = "days") <= 28) %>% 
    mutate(subset = "last 28 days")) %>%
  ggplot(aes(x = night_length, colour = subset)) + geom_density()

DF_night %>% 
  filter(Date != Sys.Date()) %>%
  mutate(recent = difftime(Sys.time(), Date, units = "days") <= 7) %>%
  # filter(night_start_time >= as.POSIXct("16:00:00", format="%H:%M:%S")) %>% 
  ggplot(aes(x = night_start_time, y = night_end_time, label = day_month)) + 
  geom_point(colour = "green") +
  geom_text(aes(colour = recent)) + 
  geom_smooth(method = "lm") + 
  theme(legend.position = "none")

DF_night %>% 
  # filter(Date != '2020-06-17') %>% 
  select(Date, night_start_time, night_end_time) %>% 
  melt(id.vars = "Date") %>% 
  ggplot(aes(x = Date, y = value, colour = variable)) + 
  geom_line() + geom_point()

DF_night %>% 
  filter(!(Date == Sys.Date() & strftime(night_start, format="%H:%M:%S") < "16:00:00")) %>%
  ggplot(aes(x = Date, y = night_length))+ 
  geom_bar(stat = "identity", fill = "blue")

prob_night %>% ggplot(aes(x = time, y = prob)) + geom_point(colour = "blue")

rbind(
  get_prob_night_start(
    DF_night, "All"),
  get_prob_night_start(
    DF_night %>% filter(difftime(Sys.time(), Date, units = "days") <= 7), "Last 7 days"),
  get_prob_night_start(
    DF_night %>% filter(difftime(Sys.time(), Date, units = "days") <= 28), "Last 28 days")) %>% 
  ggplot(aes(x = time, y = prob, colour = subset)) + geom_line()

rbind(
  get_prob_night_end(
    DF_night, "All"),
  get_prob_night_end(
    DF_night %>% filter(difftime(Sys.time(), Date, units = "days") <= 7), "Last 7 days"),
  get_prob_night_end(
    DF_night %>% filter(difftime(Sys.time(), Date, units = "days") <= 28), "Last 28 days")) %>% 
  ggplot(aes(x = time, y = prob, colour = subset)) + geom_line()

```

# start_end_boxplots

```{r start_end_boxplots}
rbind(
  DF_night %>% 
    as.data.frame() %>% select(night_start_time,night_end_time) %>% melt() %>%
    mutate(subset = "All"),
  DF_aft %>% 
    as.data.frame() %>% select(nap_start_time,nap_end_time) %>% melt() %>%
    mutate(subset = "All"),
  DF_night %>%  
    filter(difftime(Sys.time(), Date, units = "days") <= 7) %>% 
    as.data.frame() %>% select(night_start_time,night_end_time) %>% melt() %>%
    mutate(subset = "last 7 days"),
  DF_aft %>% 
    filter(difftime(Sys.time(), Date, units = "days") <= 7) %>% 
    as.data.frame() %>% select(nap_start_time,nap_end_time) %>% melt() %>%
    mutate(subset = "last 7 days")) %>%
  ggplot(aes(x = variable , y = value, fill = subset)) + geom_boxplot()
```

# night_start v.

```{r night_start_v}
inner_join(DF_aft, DF_night, c("Date", "day_month")) %>%
  ggplot(aes(x = nap_end_time, y = night_start_time, label = day_month)) + 
  geom_point(colour = "green") +
  geom_text(colour = "red") +
  geom_smooth(method = "lm")

inner_join(DF_aft, DF_night, c("Date", "day_month")) %>%
  ggplot(aes(x = nap_length, y = night_start_time, label = day_month)) + 
  geom_point(colour = "green") +
  geom_text(colour = "red") +
  geom_smooth(method = "lm")

DF_night %>% 
  # filter(Date != Sys.Date()) %>%
  mutate(Date = Start) %>% 
  inner_join(DF_24h_summary, by = "Date") %>%
  mutate(sleep_24h = sleep_24h / 60) %>%
  filter(sleep_24h > 6) %>%
  ggplot(aes(x = sleep_24h, y= night_start_time, label = day_month)) + 
  geom_point(colour = "green") +
  geom_text(colour = "red") +
  geom_smooth(method = "lm")

inner_join(
  DF_night %>% mutate(Date = as.Date(Start)),
  DF_24h_summary %>% 
    mutate(sleep_24h = sleep_24h / 60) %>%
    filter(Date %>% strftime(format ="%H:%M:%S") == "17:00:00") %>% 
    filter(sleep_24h > 6) %>%
    mutate(Date = as.Date(Date)),
  by = "Date") %>%
  ggplot(aes(x = sleep_24h, y =night_start_time , label = day_month)) + 
  geom_point(colour = "green") +
  geom_text(colour = "red") +
  geom_smooth(method = "lm")

inner_join(
  DF_night %>% mutate(Date = as.Date(Start)),
  DF_24h_summary %>% 
    mutate(sleep_24h = sleep_24h / 60) %>%
    filter(Date %>% strftime(format ="%H:%M:%S") == "17:00:00") %>% 
    filter(sleep_24h > 6) %>%
    mutate(Date = as.Date(Date)),
  by = "Date")  %>% 
  filter(difftime(Sys.time(), Date, units = "days") <= 8) %>% 
  ggplot(aes(x = sleep_24h, y =night_start_time , label = day_month)) + 
  geom_point(colour = "green") +
  geom_text(colour = "red") +
  geom_smooth(method = "lm")
```

# NightWeaning_temp

```{r NightWeaning_temp}
source("NightWeaning_temp.R")

print(NightWeaning_test1)

print(NightWeaning_p1)
print(NightWeaning_p2)
print(NightWeaning_p1p)
print(NightWeaning_p2p)
print(NightWeaning_p3)
print(NightWeaning_p4)
print(NightWeaning_p5)
print(NightWeaning_p6)
print(NightWeaning_p7)
print(NightWeaning_p8)


inner_join(
  DF2 %>% mutate(join_value = 1),
  data.frame(time = (seq(0:(60*13))*60 - 5*60*60 - 60), join_value = 1),
  by = "join_value") %>% 
  mutate(time2 = time + 24*60*60 + as.POSIXct(Date)) %>% 
  mutate(difftime(time2, Start)) %>%
  filter(time2 >= (Start - 3600) & time2 < (End - 3600)) %>%
  group_by(time, Description) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  dcast(time ~ Description, value.var = "count") %>%
  replace(is.na(.), 0) %>%
  mutate(prob_supervision = Supervision/(Supervision + Sleep + Awake)) %>%
  mutate(time = as.POSIXct(Sys.Date()) + time) %>% 
  ggplot(aes(x = time, y = prob_supervision)) + geom_line(colour = "blue")
```